language: php
php:
    - 5.3

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql php5-sqlite
    - echo "Alias /behat $(pwd)/web" | sudo tee -a /etc/apache2/sites-available/default
    - sudo a2enmod rewrite
    - sudo /etc/init.d/apache2 restart
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - mysql -e 'CREATE DATABASE test_myapp_test;'
    - sed s/%database_name%/myapp_test/ app/config/parameters.ini-dist | sed s/%database_login%/root/ | sed s/%database_password%// > app/config/parameters.ini
    - bin/vendors install
    - app/console --env=test doctrine:schema:create
    - sudo chmod -R 777 app/cache app/logs
    - sed 's/%hostname%/localhost\/behat/' behat.yml-dist > behat.yml

script: php behat.phar --profile=travis @BehatViewerBundle
