language: php
php:
    - 5.3
    - 5.4

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql php5-sqlite
    - echo "Alias /behat $(pwd)/web" | sudo tee -a /etc/apache2/sites-available/default
    - sudo a2enmod rewrite
    - sudo /etc/init.d/apache2 restart
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - mysql -e 'CREATE DATABASE test_myapp_test;'

before_script:
    - sed s/%database_name%/myapp_test/ app/config/parameters.ini-dist | sed s/%database_login%/root/ | sed s/%database_password%// | sed s/%secret%/ThisTokenIsNotSoSecret/ > app/config/parameters.ini
    - sed 's/%hostname%/localhost\/behat/' behat.yml-dist > behat.yml
    - bin/vendors install
    - app/console --env=test doctrine:schema:create
    - sudo chmod -R 777 app/cache app/logs

script: 
    - php behat.phar --profile=travis @BehatViewerBundle
    - curl -i -H "Accept: application/json" -X PUT -d @behat-viewer.json http://behat-viewer-ci.jubianchi.fr/analyze
