old_sound_rabbit_mq:
    connections:
        default:
            host:      %rabbitmq_host%
            port:      %rabbitmq_port%
            user:      %rabbitmq_user%
            password:  %rabbitmq_password%
            vhost:     %rabbitmq_vhost%

    producers:
        build:
            connection: default
            exchange_options: {name: 'build', type: direct}
        analyze:
            connection: default
            exchange_options: {name: 'analyze', type: direct}
        clean:
            connection: default
            exchange_options: {name: 'clean', type: direct}


    consumers:
        build:
            connection:       default
            exchange_options: {name: 'build', type: direct}
            queue_options:    {name: 'behat_viewer'}
            callback:         build_consumer
        analyze:
            connection: default
            exchange_options: {name: 'analyze', type: direct}
            queue_options:    {name: 'behat_viewer'}
            callback:         build_consumer
        clean:
            exchange_options: {name: 'clean', type: direct}
            queue_options:    {name: 'behat_viewer'}
            callback:         build_consumer
