# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

BehatViewerBundleJsRouting:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

BehatViewerRouting:
    resource: "@BehatViewerBundle/Resources/config/routing.yml"

BehatViewerWorkerBundle:
    resource: "@BehatViewerWorkerBundle/Controller/"
    type:     annotation
    prefix:   /worker

BehatViewerApiBundle:
    resource: "@BehatViewerApiBundle/Controller/"
    type:     annotation
    prefix:   /api

BehatViewerAdminBundle:
    resource: "@BehatViewerAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

BehatViewerBundle:
    resource: "@BehatViewerBundle/Controller/"
    type:     annotation

behatviewer.logout:
    pattern:   /logout
