# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

BehatViewerBundle:
    resource: "@BehatViewerBundle/Controller/"
    type:     annotation

BehatViewerBundleJsRouting:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

behatviewer.logout:
    pattern:   /logout
