BehatViewerBundleJsRouting:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

BehatViewerWorkerBundle:
    resource: "@BehatViewerWorkerBundle/Controller/"
    type:     annotation
    prefix:   /worker

BehatViewerApiBundle:
    resource: "@BehatViewerApiBundle/Controller/"
    type:     annotation
    prefix:   /api

BehatViewerAdminBundle:
    resource: "@BehatViewerAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

behatviewer.logout:
    pattern:   /logout

BehatViewerRouting:
    resource: "@BehatViewerBundle/Resources/config/routing.yml"

BehatViewerBundle:
    resource: "@BehatViewerBundle/Controller/"
    type:     annotation
