jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        jubianchi\BehatViewerBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        main:
            entity: { class: BehatViewerBundle:User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~

            form_login:
                login_path:  /login
                check_path:  /login/check

            logout:
                path:   /logout
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~

    access_control:
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/password, roles: ROLE_USER }
        - { path: ^/config, roles: ROLE_USER }
        - { path: ^/history/delete, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/project/create, roles: ROLE_USER }
