jms_security_extra:
    secure_all_services: true
    expressions: true

security:
    acl:
        connection: default

    encoders:
        BehatViewer\BehatViewerBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        main:
            entity: { class: BehatViewerBundle:User, property: username }

    access_control:
        - { path: ^/api, roles: ROLE_USER }

    firewalls:
        api:
            pattern:    ^/api
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

        secured_area:
            pattern:    ^/
            anonymous: ~

            form_login:
                login_path:  /login
                check_path:  /login/check
                default_target_path: /
                always_use_default_target_path: true

            logout:
                path:   /logout
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~
